server:
  ssl:
    key-store: classpath:gxx.p12
    key-store-password: starwhale
    key-store-type: pkcs12
    key-alias: starwhale
    key-password: starwhale
    enabled: true
  port: 8443
spring:
  banner:
    location: classpath:banner.txt